#!/bin/sh
exec tail -n +3 $0
# This file provides an easy way to add custom menu entries.  Simply type the
# menu entries you want to add after this comment.  Be careful not to change
# the 'exec tail' line above.

# find .efi file using '$ efibootmgr'
menuentry "Kali Linux" {
   search --file --set=root /EFI/kali/grubx64.efi
   chainloader /EFI/kali/grubx64.efi
}
